# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
b = np.arange(10,50)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
c = np.flip(b)
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.reshape(np.arange(0,9),(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [19]:
d = np.array([1,2,0,0,4,0])
np.nonzero(d)

(array([0, 1, 4], dtype=int64),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
np.random.randint(100,size=[3,3,3])

array([[[58, 80, 58],
        [34, 24, 88],
        [91, 80, 75]],

       [[50, 78, 84],
        [ 1,  7, 14],
        [20, 57, 48]],

       [[ 9, 33, 12],
        [13, 44, 11],
        [26, 49, 28]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [23]:
e = np.random.randint(100, size=[10,10])
print(np.min(e))
print(np.max(e))

2
99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
np.mean(np.random.randint(100, size=[30]))

47.666666666666664

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
f = np.zeros((5,5),dtype=int)
f[0,:]=1
f[-1,:]=1
f[:,0]=1
f[:,-1]=1
print(f)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [50]:
x = np.reshape(np.arange(1,10),(3,3))
np.pad(x, 1, 'constant', constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [54]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)  # Floats are represented as fractions internally, so are not exact
print(round(0.3) == round(3 * 0.1))

nan
False
False
nan
True
False
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [66]:
x = np.zeros((5,5), dtype=int)
rg = np.arange(4)
x[rg+1,rg]=[1,2,3,4]
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [77]:
x = np.arange(1,(6*7*8)+1).reshape(6,7,8)
res = np.where(x == 100)
coord = np.hstack([res[0], res[1], res[2]])
print(coord)

[1 5 3]


In [78]:
x[1,5,3]

100

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [79]:
np.linalg.norm(np.random.randint(100, size=[5,5]))

309.8354401936615

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [90]:
x = np.arange(10)
np.negative(x, where=((x>3) & (x<8)) )

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 29. How to round away from zero a float array ? (★☆☆)

In [99]:
x = np.array([-5.4, -2.3, 0.0, 1.2, 7.8])
y = np.floor(x, where=(x<0))
np.ceil(x, where=(x>0))

array([-6., -3.,  0.,  2.,  8.])

#### 30. How to find common values between two arrays? (★☆☆)

In [100]:
x = np.array([2,4,6,8])
y = np.array([1,2,3,4])
np.intersect1d(x,y)

array([2, 4])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [105]:
np.emath.sqrt(-1) # np.squt gives error for negative - emath seems to treat as positive

1j

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [108]:
np.random.randint(100, size=10)

array([88, 71, 93, 29, 77, 39, 55, 59, 36, 19])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [109]:
np.random.rand(10)

array([0.92987668, 0.84026907, 0.87907989, 0.72141531, 0.93369182,
       0.89582038, 0.40871753, 0.55983037, 0.4789467 , 0.86106723])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [110]:
np.sort(np.random.rand(10))

array([0.0229776 , 0.11684214, 0.18342833, 0.25794992, 0.28497209,
       0.49567937, 0.86842007, 0.8695645 , 0.97391053, 0.9847258 ])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [111]:
x = np.random.rand(5)
y = np.random.rand(5)
np.array_equal(x,y)

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [114]:
x = np.random.randint(100, size=10)
m = np.amax(x)
x[x==m] = 0
x

array([50, 11,  0, 57, 69, 74, 61, 41, 27, 18])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [126]:
sc = np.random.uniform(0,100)
print(sc)
ind = np.argmin((np.absolute(x-sc)))
print(x[ind])

63.30447037333248
61


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [135]:
f = np.array([1.11, 2.23, 3.34, 5.67, 8.98], dtype='f')
print(f.dtype)
i = f.astype(int)
print(i)
print(i.dtype)

float32
[1 2 3 5 8]
int32


#### 59. How to sort an array by the nth column? (★★☆)

In [145]:
sort_col = 2
ar = np.array([[1,5,3],[4,6,2],[3,2,7]])
ind = np.argsort(ar[:,sort_col])   # get indices for order of sort colunm
ar = ar[ind]                       # re-write array in this order
ar

array([[4, 6, 2],
       [1, 5, 3],
       [3, 2, 7]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [162]:
nums = np.random.randint(0,2,(4,10))
print(nums)
print((~nums.any(axis=0)).any())  # checks for any True for evaluated condition - default is "no value"

[[1 1 0 0 1 1 0 1 0 1]
 [1 1 1 0 1 1 0 1 1 1]
 [0 0 1 0 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0 1]]
True


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [168]:
x = np.array([1,2,3,4,5])
np.insert(x, x[0:-1], 0)

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

#### 72. How to swap two rows of an array? (★★★)

In [173]:
ar = np.array([[1,5,3],[4,6,2],[3,2,7]])
temp = np.copy(ar[0])
ar[0] = ar[1]
ar[1] = temp
ar

array([[4, 6, 2],
       [1, 5, 3],
       [3, 2, 7]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [176]:
x = np.array([True, False, False, True])
print(np.invert(x))
y = np.array([2.3, -4.5, 6.7])
print(np.negative(y))

[False  True  True False]
[-2.3  4.5 -6.7]


#### 83. How to find the most frequent value in an array?

In [178]:
print(nums)
print(np.bincount(nums.flatten()).argmax())

[[1 1 0 0 1 1 0 1 0 1]
 [1 1 1 0 1 1 0 1 1 1]
 [0 0 1 0 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0 1]]
1


#### 89. How to get the n largest values of an array (★★★)

In [182]:
n = 3
arr = np.array([2, 0,  1, 5, 4, 1, 9])
sorted_index = np.argsort(arr)
arr[sorted_index[-n]]

4

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [183]:
arr = np.array([[1,2,3],[3,3,5],[1,2,3],[4,5,6],[3,3,5]])
np.unique(arr, axis=0)

array([[1, 2, 3],
       [3, 3, 5],
       [4, 5, 6]])